pluginManagement {
    repositories {
        //mavenLocal()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    versionCatalogs {
        libs {
            version('mapstruct', '1.5.5.Final')
            version('jakarta-validation', '3.0.2')

            library('mapstruct', 'org.mapstruct', 'mapstruct').versionRef('mapstruct')
            library('mapstruct-processor', 'org.mapstruct', 'mapstruct-processor').versionRef('mapstruct')
            library('jakarta-validation-api', 'jakarta.validation', 'jakarta.validation-api').versionRef('jakarta-validation')
        }
    }
}

buildCache {
    local {
        directory = new File(rootDir, 'build-cache')
    }
}

rootProject.name = 'RetoReactivoPersona'

include ':app-service'
include ':model'
include ':usecase'
project(':app-service').projectDir = file('./applications/app-service')
project(':model').projectDir = file('./domain/model')
project(':usecase').projectDir = file('./domain/usecase')
include ':reactive-web'
project(':reactive-web').projectDir = file('./infrastructure/entry-points/reactive-web')
include ':r2dbc-postgresql'
project(':r2dbc-postgresql').projectDir = file('./infrastructure/driven-adapters/r2dbc-postgresql')
include ':webflux-client'
project(':webflux-client').projectDir = file('./infrastructure/driven-adapters/webflux-client')
include ':bootcamp-client-adapter'
project(':bootcamp-client-adapter').projectDir = file('./infrastructure/driven-adapters/bootcamp-client-adapter')
include ':report-client-adapter'
project(':report-client-adapter').projectDir = file('./infrastructure/driven-adapters/report-client-adapter')